#!/bin/bash

# NOTE: These may vary between distros.
SITE_CONFIG_DIR='/etc/apache2/sites-available'
WEB_DIR='/var/www'
LOG_DIR='/var/log/apache2'

PROGRAM=$(basename $0)
ARGV=($@)
ARGC=$#
SITE="$1"
CONFIG_FILE="$SITE_CONFIG_DIR/$SITE"

# Usage info.
if [ $ARGC -ne 1 ] || [ "${ARGV[1]}" == '--help' ] ; then
  echo -e "$PROGRAM by Craig Buchek (BoochTek, LLC)\n"
  echo -e "Create directories and a basic config file for an Apache 2 web site.\n"
  echo -e "Usage: $PROGRAM SITENAME"
  echo -e "Example: sudo $PROGRAM boochtek.com"
  exit 0;
fi

# Create required directories.
mkdir -p $WEB_DIR/$SITE/public
mkdir -p $LOG_DIR/$SITE

# Add a basic config file for the site, unless it already exists.
[ -e $CONFIG_FILE ] || cat > $CONFIG_FILE <<CONFIG
<VirtualHost *:80>
  ServerName $SITE
  UseCanonicalName On

  CustomLog $LOG_DIR/$SITE/access.log combined
  ErrorLog $LOG_DIR/$SITE/error.log

  DocumentRoot $WEB_DIR/$SITE/public
  <Directory $WEB_DIR/$SITE/public>
    AllowOverride All
    Options FollowSymLinks
    Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>
CONFIG
