#!/bin/bash

# NOTE: These may vary between distros.
SITE_CONFIG_DIR='/etc/apache2/sites-available'
WEB_DIR='/var/www'
LOG_DIR='/var/log/apache2'

PROGRAM=$(basename $0)
ARGS=($@)
SITE="$1"
shift; ALIASES="$*"
CONFIG_FILE="$SITE_CONFIG_DIR/$SITE"

# Usage info.
if [ "${#ARGS[@]}" -lt 2 ] || [ "${ARGS[1]}" == "--help" ] ; then
  echo -e "$PROGRAM by Craig Buchek (BoochTek, LLC)\n"
  echo -e "Add domain name aliases to the config file for an Apache 2 web site.\n"
  echo -e "Usage: $PROGRAM SITENAME SITEALIAS..."
  echo -e "Example: sudo $PROGRAM boochtek.com www.boochtek.com boochtech.com www.boochtech.com"
  exit 0;
fi

# Verify that the config file exists and is writeable.
if [ ! -w $CONFIG_FILE ]; then
  echo "$0: cannot write to config file for $SITE ($CONFIG_FILE)"
  exit 1;
fi

# Determine where to add the alias(es) in the config file. Put them after the last alias, or the site name.
ADD_AFTER_LINE=$(grep -in '^[[:space:]]*ServerAlias' $CONFIG_FILE | tail -1 | cut -f1 -d:)
if [ -z "$ADD_AFTER_LINE" ]; then
  ADD_AFTER_LINE=$(grep -in '^[[:space:]]*ServerName' $CONFIG_FILE | tail -1 | cut -f1 -d:)
fi

# Add each requested alias.
for ALIAS in $ALIASES; do
  if ! grep -iq "^[[:space:]]*ServerAlias[[:space:]]*$ALIAS" $CONFIG_FILE ; then
    sed -i -e "$ADD_AFTER_LINE a \\ \\ ServerAlias $ALIAS" $CONFIG_FILE
    ADD_AFTER_LINE=$(expr $ADD_AFTER_LINE + 1)
  fi
done
