#!/bin/bash

# NOTE: These may vary between distros.
SITE_CONFIG_DIR='/etc/apache2/sites-available'
WEB_DIR='/var/www'
LOG_DIR='/var/log/apache2'

PROGRAM=$(basename $0)
ARGV=($@)
ARGC=$#
SITE="$1"
OWNER="$2"
CONFIG_FILE="$SITE_CONFIG_DIR/$SITE"

# Usage info.
if [ $ARGC -ne 2 ] || [ "${ARGV[1]}" == '--help' ] || [ "${ARGV[2]}" == '--help' ] ; then
  echo -e "$PROGRAM by Craig Buchek (BoochTek, LLC)\n"
  echo -e "Set owner of a web site directory, config file, and log files for an Apache 2 web site.\n"
  echo -e "Usage: $PROGRAM SITENAME USERNAME[:GROUPNAME]"
  echo -e "Example: sudo $PROGRAM boochtek.com booch:www-data"
  exit 0;
fi

# Make sure the directories exist.
mkdir -p $WEB_DIR/$SITE/public
mkdir -p $LOG_DIR/$SITE

# Change ownership, as requested.
chown -R $OWNER $CONFIG_FILE
chown -R $OWNER $WEB_DIR/$SITE
chown -R $OWNER $LOG_DIR/$SITE

# Change permissions, as appropriate.
chmod -R g+ws,a+X $WEB_DIR/$SITE
